### ISSUE TITLE
aws what level of access is required? 

### ISSUE THREAD

**Issue by kid101** [twistlock/cloud-discovery#14]
when using 
`curl -k -v -u admin:pass --raw --data \
'{"credentials": [{"id":"<AWS_ACCESS_KEY>","secret":"<AWS_ACCESS_PASSWORD>"}]}' \
 https://localhost:9083/discover`

I get an empty response from the server:
` upload completely sent off: 100 out of 100 bytes
TLSv1.2 (IN), TLS alert, Client hello (1):
 Empty reply from server
`
Please let me know all the read permissions required.

**Comment by kid101** [comment]
Only ECR, ECS, EKS and lambda are supported at the movement.

**Comment by shikharka** [comment]
Hi,
Did you get the solution?
I have lambda functions but still get 

> * upload completely sent off: 100 out of 100 bytes
> * Empty reply from server
> * Connection #0 to host localhost left intact
> curl: (52) Empty reply from server

Can I get a help on this?
